apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.variables.common.environment }}-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: {{ .Values.variables.common.environment }}-infra
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: {{ .Values.variables.common.gitRepo }}
            revision: {{ .Values.variables.common.revision }}
            files:
            - path: {{ .Values.variables.common.option }}/environments/{{ .Values.variables.common.environment }}/variables/values.yaml
        - list:
            elements: []
            elementsYaml: "{{ .variables.infrastructure | toJson }}" 
  template:
    metadata:
      namespace: argocd
      name: '{{.variables.common.project}}-{{.variables.common.environment}}-{{.variables.common.type}}-{{.product}}-{{.productType}}-{{.name}}'
    spec:
      project: '{{.variables.common.project}}'
      sources:
      - chart: '{{.chart}}'
        repoURL: '{{.repoUrl}}'
        targetRevision: '{{.chartVersion}}'
        helm:
          valueFiles:
          - $values/{{ .Values.variables.common.option }}/environments/{{.variables.common.environment}}/infrastructure/values/{{.chart}}/values.yaml
      - repoURL: {{ .Values.variables.common.gitRepo }}
        targetRevision: {{ .Values.variables.common.revision }}
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.variables.common.project}}-{{.variables.common.environment}}-{{.variables.common.type}}-{{.product}}-{{.productType}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata: 
          labels:
            project: '{{.variables.common.project}}-{{.variables.common.environment}}-{{.variables.common.type}}-{{.product}}-{{.productType}}'
