apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: silo98-200-primary-shared-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: silo98-200-primary-shared-infra
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/sadoha/ArgoCD.git
            revision: stan-sandbox
            files:
            - path: option98/environments/200/variables/values.yaml
        - list:
            elements: []
            elementsYaml: "{{ .variables.infrastructure | toJson }}" 
  template:
    metadata:
      namespace: argocd
      name: '{{.variables.common.project}}-{{.variables.common.environment}}-{{.variables.common.type}}-{{.product}}-{{.productType}}-{{.name}}'
    spec:
      project: '{{.variables.common.project}}'
      sources:
      - chart: '{{.chart}}'
        repoURL: '{{.repoUrl}}'
        targetRevision: '{{.chartVersion}}'
        helm:
          valueFiles:
          - $values/option98/environments/{{.variables.common.environment}}/infrastructure/values/{{.chart}}/values.yaml
      - repoURL: 'https://github.com/sadoha/ArgoCD.git'
        targetrevision: stan-sandbox
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.variables.common.project}}-{{.variables.common.environment}}-{{.variables.common.type}}-{{.product}}-{{.productType}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata: 
          labels:
            project: '{{.variables.common.project}}-{{.variables.common.environment}}-{{.variables.common.type}}-{{.product}}-{{.productType}}'
