apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project1-all-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: project1-all-apps
spec:
  generators:
    - git:
        repoURL: https://github.com/sadoha/ArgoCD.git
        revision: HEAD
        directories:
          - path: option4/argocd/environments/*
  template:
    metadata:
      namespace: argocd
      name: project1-{{path.basename}}-all-apps
    spec:
      project: default
      sources:
      - repoURL: https://github.com/sadoha/ArgoCD.git
        targetRevision: HEAD
        path: option4/argocd/projects
      - repoURL: https://github.com/sadoha/ArgoCD.git
        targetRevision: HEAD
        path: option4/argocd/environments/{{path.basename}}/applicationsets
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
