apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grouped-apps-environment1
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sadoha/ArgoCD.git
        revision: stan-sandbox
        directories:
          - path: option99/environments/environment-1/*/*
  template:
    metadata:
      name: "{{path.basename}}-{{path.dirname | basename}}"  # appname-groupname
    spec:
      project: default
      source:
        repoURL: https://github.com/sadoha/ArgoCD.git
        path: option99/environments/environment-1/{{path.dirname | basename}}/{{path.basename}}
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.dirname | basename}}"  # Use group name as namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncWave: |
        {{ if eq path.basename "app2" }}
        1
        {{ else if eq path.basename "app4" }}
        2
        {{ else }}
        0
        {{ end }}
