apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-100-applicationset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: apps-100-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/sadoha/ArgoCD.git
            revision: HEAD
            files:
            - path: option5/argocd/environments/100/variables/values.yaml
        - list:
            elements: []
            elementsYaml: "{{ .variables.products | toJson }}" 
  template:
    metadata:
      namespace: argocd
      name: '{{.name}}'
    spec:
      project: '{{.variables.common.project}}'
      sources:
      - repoURL: https://github.com/sadoha/ArgoCD.git
        targetRevision: HEAD
        path: 'helm/{{.chart}}'
        helm:
          parameters:
            - name: image.tag
              value: '{{.appVersion}}'
          valueFiles:
          - $values/option5/argocd/environments/{{.variables.common.environment}}/products/{{.product}}/{{.appName}}/values.yaml
      - repoURL: 'https://github.com/sadoha/ArgoCD.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.variables.common.environment}}-apps'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata: 
          labels:
            project: '{{.variables.common.environment}}-apps'
          annotations:
            annotations: '{{.variables.common.environment}}-apps'
