apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: full-environment-deploy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: full-environment-deploy
spec:
  generators:
    - git:
        repoURL: https://github.com/sadoha/ArgoCD.git
        revision: HEAD
        directories:
          - path: option3/argocd/applicationsets/*
          - path: option3/argocd/applicationsets/appset-generator-git-full-environment-deploy.yaml
            exclude: true
  template:
    metadata:
      namespace: argocd
      name: full-environment-deploy
    spec:
      project: default
      sources:
      - repoURL: https://github.com/sadoha/ArgoCD.git
        targetRevision: HEAD
        path: option3/argocd/projects
      - repoURL: https://github.com/sadoha/ArgoCD.git
        targetRevision: HEAD
        path: option3/argocd/applicationsets
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
