apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shared-100-applicationset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: shared-100-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/sadoha/ArgoCD.git
            revision: HEAD
            files:
            - path: option3/argocd/environments/100/components/key-components-infra-apps.yaml
        - list:
            elements: []
            elementsYaml: "{{ .key.components | toJson }}" 
  template:
    metadata:
      namespace: argocd
      name: '{{.name}}'
    spec:
      project: '{{.key.common.project}}'
      sources:
      - chart: '{{.chart}}'
        repoURL: '{{.repoUrl}}'
        targetRevision: '{{.chartVersion}}'
        helm:
          valueFiles:
          - $values/option3/argocd/environments/{{.key.common.environment}}/applications/{{.chart}}/values.yaml
      - repoURL: 'https://github.com/sadoha/ArgoCD.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: 'applications-{{.key.common.environment}}-infra'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata: 
          labels:
            project: 'applications-{{.key.common.environment}}-infra'
          annotations:
            annotations: 'applications-{{.key.common.environment}}-infra'
