apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-100-applicationset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: project-100-applicationset
spec:
  generators:
    - git:
        repoURL: https://github.com/sadoha/ArgoCD.git
        revision: HEAD
        directories:
          - path: option3/*/environments/*/apps/*
  template:
    metadata:
      namespace: argocd
      name: "{{path[1]}}-{{path[3]}}-{{path.basename}}"
    spec:
      project: project-100
      sources:
      - repoURL: https://github.com/sadoha/ArgoCD.git
        targetRevision: HEAD
        path: helm/app
        helm:
          valueFiles:
          - $values/option3/{{path[1]}}/environments/{{path[3]}}/apps/{{path.basename}}/values.yaml
      - repoURL: 'https://github.com/sadoha/ArgoCD.git'
        targetRevision: HEAD
        ref: values
      destination:
        namespace: "{{path[3]}}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata: 
          labels:
            project: "{{path[3]}}-{{path.basename}}"
          annotations:
            annotations: "{{path[3]}}-{{path.basename}}"
